# Configuration file version
VERSION: '0.2.2'

# Loadshedding area
# Should correspond to the areas beneath the stages in the SCHEDULE_CSV file
# Area names are those of the original source documentation
AREA: '<AREA>'
# Query Mode
# DIRECT to directly query the current stage from the Eskom API
# The following settings are applicable:
#   API_URL: https://loadshedding.eskom.co.za/LoadShedding/GetStatus
# LOADSHEDDING_THINGAMABOB to query a stage schedule .csv from the cloud
# The following settings are applicable:
#   API_URL: <AWS Lambda Gateway URL>
QUERY_MODE: <QUERY_MODE>
# Loadshedding schedule
SCHEDULE_CSV: '<PATH_TO_SCHEDULE.CSV>'
# API Address to get loadshedding stage
API_URL: "<PATH_TO_CURRENT_STAGE_SCHEDULE_QUERY_API>"

# Command to run just before or during loadshedding
# Examples:
#   "sudo /usr/sbin/s2disk" - Hibernate
#   "sudo poweroff" - Shutdown
CMD: "<COMMAND>"

# Show GUI Notification with timeout before running action specified by CMD
#   Allows the user to cancel the action
GUI_NOTIFICATION: True

# Pad the start time with PAD_START minutes before the time indicated on the
# schedule
# Used to run the command before loadshedding actually starts
PAD_START: 17 # minutes
# Ignore the last IGNORE_END minutes of each interval on the schedule
# Used to create a deadzone in case the power is restored earlier than the
# schedule indicates
IGNORE_END: 30 # minutes

# Check if this script has already run the loadshedding command (CMD) during
# this loadshedding block
# If so, don't run the command again
RAN_CHECK: True
