# Loadshedding area
# Should correspond to the areas beneath the stages in the SCHEDULE_CSV file
# Area names are those of the original source documentation
AREA: '8B'
# Loadshedding schedule
SCHEDULE_CSV: 'schedules/load_shedding_city_power.csv'

# Command to run just before or during loadshedding
# Examples:
#   "sudo /usr/sbin/s2disk" - Hibernate
#   "sudo poweroff" - Shutdown
CMD: "sudo /usr/sbin/s2disk"

# Show GTK Notification with timeout before running action specified by CMD
#   Allows the user to cancel the action
GTK_NOTIFICATION: True

# Pad the start time with PAD_START minutes before the time indicated on the
# schedule
# Used to run the command before loadshedding actually starts
PAD_START: 17 # minutes
# Ignore the last IGNORE_END minutes of each interval on the schedule
# Used to create a deadzone in case the power is restored earlier than the
# schedule indicates
IGNORE_END: 30 # minutes
