# API Address to get loadshedding stage
API_URL: "http://loadshedding.eskom.co.za/LoadShedding/GetStatus"
# Timestamped stage logfile
LOGSTAGE: "stage.log"
# Action and crash logfile
LOG: "log.log"

MIN_OFFSET: 4 # minutes
MAX_OFFSET: 17 # minutes

# GTK Notication timeout
NOTIFICATION_TIMEOUT: 120
